#!/usr/bin/env bun
/**
 * schedule.yaml -> launchd plists.
 *
 *   bun deploy/gen.mjs            # render to deploy/launchd/, show a diff
 *   bun deploy/gen.mjs --install  # also copy into ~/Library/LaunchAgents and load
 *
 * Generated files are committed so the diff is reviewable: a scheduling change
 * should show up in a PR like any other change.
 *
 * Schedule parsing lives in lib/schedule.mjs so this and the foreground
 * supervisor (orchestrator/run.mjs) always read the same jobs from the same
 * file -- two parsers is how the two execution modes would drift.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import path from "node:path";
import { loadSchedule, toSeconds, ROOT } from "../lib/schedule.mjs";
const OUT = path.join(ROOT, "deploy", "launchd");
const DEFAULT_PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
// Resolve at job runtime so committed plists are identical whether rendered from
// the deployed checkout, a disposable ticket worktree, or a CI checkout.
const DEPLOY_ROOT = '"${FACTORY_ROOT:-$HOME/Develop/factory}"';

const expand = (p) => p.replace(/^~/, homedir());

const xml = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function launchdPath(environmentPath = process.env.PATH, home = homedir()) {
  const entries = (environmentPath || DEFAULT_PATH).split(":").filter(Boolean);
  for (const entry of [path.join(home, ".bun", "bin"), path.join(home, ".local", "bin")]) {
    if (!entries.includes(entry)) entries.push(entry);
  }
  return entries.join(":");
}

export function plist(job, defaults, environmentPath = launchdPath()) {
  const label = `${defaults.label_prefix}.${job.name}`;
  const logDir = expand(defaults.log_dir || "~/Library/Logs");
  const args = ["/bin/bash", "-lc", `cd ${DEPLOY_ROOT} && ${job.command}`];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <!-- GENERATED by deploy/gen.mjs from config/schedule.yaml. Do not edit. -->
    <key>Label</key>
    <string>${label}</string>

    <key>ProgramArguments</key>
    <array>
${args.map((a) => `        <string>${xml(a)}</string>`).join("\n")}
    </array>

    <key>StartInterval</key>
    <integer>${toSeconds(job.every)}</integer>

    <key>RunAtLoad</key>
    <${defaults.run_at_load === true ? "true" : "false"}/>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${xml(environmentPath)}</string>
    </dict>

    <!-- .out.log, not .log: a job whose wrapper already writes its own
         structured log would otherwise have two writers on one file. -->
    <key>StandardOutPath</key>
    <string>${logDir}/${job.name}.out.log</string>
    <key>StandardErrorPath</key>
    <string>${logDir}/${job.name}.err.log</string>

    <key>ProcessType</key>
    <string>Background</string>
    <key>LowPriorityIO</key>
    <true/>
</dict>
</plist>
`;
}

export function installPlists(enabled, defaults, {
  outDir = OUT,
  agentsDir = path.join(homedir(), "Library/LaunchAgents"),
  run = execFileSync,
  uid = process.getuid(),
} = {}) {
  mkdirSync(agentsDir, { recursive: true });
  for (const job of enabled) {
    const label = `${defaults.label_prefix}.${job.name}`;
    const src = path.join(outDir, `${label}.plist`);
    const dst = path.join(agentsDir, `${label}.plist`);
    writeFileSync(dst, readFileSync(src));
    try { run("launchctl", ["bootout", `gui/${uid}/${label}`], { stdio: "ignore" }); } catch {}
    run("launchctl", ["bootstrap", `gui/${uid}`, dst]);
    console.log(`  loaded    ${label}`);
  }
}

export function main({ install = process.argv.includes("--install") } = {}) {
  const { defaults, jobs } = loadSchedule();
  mkdirSync(OUT, { recursive: true });

  const enabled = jobs.filter((j) => j.enabled !== false);
  const skipped = jobs.filter((j) => j.enabled === false);

  for (const job of enabled) {
    const file = path.join(OUT, `${defaults.label_prefix}.${job.name}.plist`);
    const next = plist(job, defaults);
    const prev = existsSync(file) ? readFileSync(file, "utf8") : null;
    writeFileSync(file, next);
    console.log(`${prev === next ? "  unchanged" : prev ? "  updated  " : "  created  "} ${path.basename(file)}  (every ${job.every})`);
  }
  for (const job of skipped) console.log(`  disabled  ${job.name}  — ${String(job.why || "").slice(0, 60)}`);

  if (!install) {
    console.log(`\n${enabled.length} job(s) rendered to deploy/launchd/. Re-run with --install to load them.`);
    return;
  }

  installPlists(enabled, defaults);
}

if (import.meta.main) main();
